# Generated by Django 4.2.7 on 2024-02-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
