# Generated by Django 4.2.7 on 2024-02-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myapp_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
