# Generated by Django 4.2.7 on 2024-02-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_myapp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myapp',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
