# Generated by Django 4.2.7 on 2024-02-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_myapp_description_alter_myapp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='catrgory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
