# Generated by Django 4.2.7 on 2024-02-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_myapp_catrgory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='catrgory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
