# Generated by Django 4.2.7 on 2024-02-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_catrgory_myapp_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myapp',
            name='category',
        ),
        migrations.AddField(
            model_name='myapp',
            name='categories',
            field=models.ManyToManyField(to='myapp.category'),
        ),
    ]
